"$schema" = 'https://starship.rs/config-schema.json'

format = """\
[╭╴](bold 238)$directory\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
$git_branch\
$git_status\
$line_break\
[╰](bold 238)$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = 'white'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = 'blue'
color_aqua = 'cyan'
color_green = 'green'
color_orange = '#d65d0e'
color_purple = 'purple'
color_red = 'red'
color_yellow = 'yellow'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:red"
format = "[ $path ]($style)"
truncation_length = 3

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = "󰊢"
style = "fg:yellow"
format = '[[$symbol $branch](fg:yellow)]($style)'

[git_status]
conflicted = "⚔️ "
ahead = "[${count} ](fg:color_fg0)"
behind = "[${count} ](fg:color_fg0)"
diverged = "[${ahead_count} ](fg:color_fg0) [${behind_count}](fg:color_fg0)"
untracked = "[${count} ](fg:color_fg0)"
stashed = "[${count} ](fg:color_fg0)"
modified = "[${count} ](fg:color_fg0)"
renamed = "[${count}󰑕 ](bg:color_bg1 fg:blue)"
staged = "[${count}󱓺 ](bg:color_bg1 fg:green)"
deleted = "[ ${count} ](bg:color_bg1 fg:red)"
style = "fg:black"
format = '[[ ($all_status$ahead_behind )](fg:black)]($style)'

[nodejs]
symbol = " "

[lua]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[rust]
symbol = ""

[golang]
symbol = ""

[php]
symbol = ""

[java]
symbol = ""

[kotlin]
symbol = ""

[haskell]
symbol = ""

[python]
symbol = ""

[docker_context]
symbol = ""

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[󰄾](bold fg:color_green)'
error_symbol = '[󰄾](bold fg:color_red)'
vimcmd_symbol = '[󰄾](bold fg:color_green)'
vimcmd_replace_one_symbol = '[󰄾](bold fg:color_purple)'
vimcmd_replace_symbol = '[󰄾](bold fg:color_purple)'
vimcmd_visual_symbol = '[󰄾](bold fg:color_yellow)'
